-- Katalog veritabanı kurulumu.
-- Supabase panelinde: SQL Editor > New query > bu dosyanın tamamını yapıştır > Run.
-- Tekrar çalıştırmak güvenlidir.

create table if not exists kategoriler (
  slug text primary key,
  ad   text not null,
  sira int  not null default 0
);

create table if not exists alt_kategoriler (
  kat  text not null references kategoriler(slug) on update cascade,
  slug text not null,
  ad   text not null,
  sira int  not null default 0,
  primary key (kat, slug)
);

create table if not exists urunler (
  id        bigint generated by default as identity primary key,
  ad        text not null,
  kod       text not null default '',
  barkod    text not null default '',
  tedarikci text not null default '',
  olcu      text not null default '',
  alis      numeric(12,2) not null default 0,   -- alış, KDV hariç
  alis_kdv  numeric(12,2) not null default 0,   -- alış, KDV dahil
  fiyat     numeric(12,2) not null default 0,   -- satış, KDV dahil
  kat       text not null,
  alt       text not null,
  gorseller text[] not null default '{}',       -- depodaki dosya adları (urunler/k ve urunler/b)
  silindi   timestamptz,                        -- dolu ise ürün silinmiş sayılır (geri alınabilir)
  eklenme   timestamptz not null default now(),
  foreign key (kat, alt) references alt_kategoriler(kat, slug) on update cascade
);
create index if not exists ix_urunler_kat on urunler(kat, alt);

-- Excel'den gelen ürünler satır numarasını id olarak kullanır; yeni eklenenler 100000'den başlar.
do $$
begin
  if (select coalesce(max(id), 0) from urunler) < 100000 then
    alter table urunler alter column id restart with 100000;
  end if;
end $$;

-- Yalnızca giriş yapmış kullanıcı okuyup yazabilir.
alter table kategoriler     enable row level security;
alter table alt_kategoriler enable row level security;
alter table urunler         enable row level security;

drop policy if exists "giris yapan" on kategoriler;
drop policy if exists "giris yapan" on alt_kategoriler;
drop policy if exists "giris yapan" on urunler;
create policy "giris yapan" on kategoriler     for all to authenticated using (true) with check (true);
create policy "giris yapan" on alt_kategoriler for all to authenticated using (true) with check (true);
create policy "giris yapan" on urunler         for all to authenticated using (true) with check (true);

-- Ürün fotoğrafları deposu. Fotoğraflar adresini bilen herkesçe görüntülenebilir
-- (fiyat / tedarikçi bilgisi içermez); yükleme ve silme yalnızca giriş yapan kullanıcıya açıktır.
insert into storage.buckets (id, name, public)
values ('urunler', 'urunler', true)
on conflict (id) do update set public = true;

drop policy if exists "urun gorseli yukle"    on storage.objects;
drop policy if exists "urun gorseli guncelle" on storage.objects;
drop policy if exists "urun gorseli sil"      on storage.objects;
create policy "urun gorseli yukle"    on storage.objects for insert to authenticated with check (bucket_id = 'urunler');
create policy "urun gorseli guncelle" on storage.objects for update to authenticated using (bucket_id = 'urunler');
create policy "urun gorseli sil"      on storage.objects for delete to authenticated using (bucket_id = 'urunler');
